config/routes.rb
App::Application.routes.draw do
  resources :tasks
  root :to => 'application#index'

end

app/models/task.rb
class Task
  include Mongoid::Document
  field :body, type: String
  field :complete, type: Boolean
  field :due, type: DateTime
  field :title, type: String

  #validations
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
# Standard Rails controller.
# No need to implement def new and def edit since the generation of HTML
# is moved from the server side to the client side.
class TasksController < ApplicationController

  def index
    render :json => Task.all
  end

  def show
    render :json => Task.find(params[:id])
  end

  def create
    document = Task.create! params[:task]
    render :json => document
  end

  def update
    render :json => Task.find(params[:id]).update_attributes!(params[:task])
  end

  def destroy
    render :json => Task.find(params[:id]).destroy
  end

  def edit

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/index.html.haml
// This will generate an HTML page so that we can later on add stuff to it.
#app

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Untitled"

    / Included CSS Files
    = stylesheet_link_tag "application"
    / Included JS Files
    = javascript_include_tag "application"
    / Added the following files as a JS template
    = csrf_meta_tags

    = render :partial => 'templates/show_task'
    = render :partial => 'templates/edit_task'
    = render :partial => 'templates/index'
  %body
    = yield

app/views/tasks/_form.html.haml
= form_for(@task) do |f|
  - if @task.errors.any?
    #error_explanation
      %h5
        Please correct the following
        - pluralize(@task.errors.count, "error")
        and resubmit the form:

      %ul
      - @task.errors.full_messages.each do |msg|
        %li
          = msg

  %fieldset
    %legend
      %h3
        Task:
    .field
      = f.label :title
      %br
      = f.text_field :title
    .field
      = f.label :body
      %br
      = f.text_field :body
    .field.two
      = f.label :due
      %br
      = f.datetime_select :due
    .field
      = f.label :complete
      %br
      = f.check_box :complete
    .actions
      = f.submit 'Create Task', :class => 'button radius'

app/views/tasks/edit.html.haml
= render 'form'

= link_to 'Show', @task, :class => "button radius" |
= link_to 'Back', tasks_path, :class => "button radius"

app/views/tasks/index.html.haml
%form
  %fieldset
    %legend
      %h3
        Listing tasks
    .row

      %table
        %tr
          %th Title
          %th Body
          %th Due
          %th Complete
          %th
          %th
          %th


          - @tasks.each do |task|
            %tr
              %td= task.title
              %td= task.body
              %td= task.due
              %td= task.complete
              %td.button.small.radius.dropdown{:href => "#"}
                Do more
                %ul
                  %li= link_to 'Show', task
                  %li= link_to 'Edit', edit_task_path(task)
                  %li= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
%br

  = link_to 'New Task', new_task_path, :class => "button radius"

app/views/tasks/new.html.haml
= render 'form'

= link_to 'Back', tasks_path, :class => "button radius"

app/views/tasks/show.html.haml
%form
  %fieldset
    %legend#notice
      = notice

    %p
      %b Title:
      = @task.title

    %p
      %b Body:
      = @task.body

    %p
      %b Due:
      = @task.due

    %p
      %b Complete:
      = @task.complete


  = link_to 'Edit', edit_task_path(@task), :class => "button radius" |
  = link_to 'Back', tasks_path, :class => "button radius"

app/views/templates/_edit_task.haml
%script{:id => 'edit_task-template', :type => 'text/x-handlebars-template'}
  .row
    .eight.centered.columns
      %h3.alert-box.alert
        Please edit the details here
      %form
        %input#title{:value => '{{task.title}}'}
        %input#body{:value => '{{task.body}}'}
        %input#due{:value => '{{task.due}}'}
        %input#complete{:value => '{{task.complete}}'}
        %a.button.radius#update UPDATE


  = link_to 'Show', @task, :class => "button radius" |
  = link_to 'Back', "/", :class => "button radius"

app/views/templates/_index.haml
%script{:id => 'index-template', :type => 'text/x-handlebars-template'}
  %form
    %fieldset
      %legend
        %h3
          Listing tasks
      .row

        %table
          %tr
            %th Title
            %th Body
            %th Due
            %th Complete
            %th
            %th
            %th


            -#- @tasks.each do |task|
            {{#each tasks}}
            %tr
              %td {{title}}
              %td {{body}}
              %td {{due}}
              %td {{complete}}
              %td
                .button.small.radius{:href  => '#', :class => "show" }  Show
                %a.button.small.radius{:href  => '#/tasks/edit/{{_id}}', :class => "edit" }  Edit
                .button.small.radius{:href  => '#', :id => '{{_id}}', :class => "delete" }  Delete
            {{/each}}
  %br

  %fieldset
    %legend
      %h3
        Task:
    .field
      = label_tag :title

      %br
      = text_field_tag :title
    .field
      = label_tag :body
      %br
      = text_area_tag :body
    .field.two
      = label_tag :due
      %br
      = text_field_tag :due
    .field
      = label_tag :complete
      %br
      = check_box_tag :complete
    .actions
      = submit_tag 'Create Task', :class => 'button radius', :id => 'submit'

app/views/templates/_show_task.haml
%script{:id => 'show_task-template', :type => 'text/x-handlebars-template'}

  %form
    %fieldset
      %legend#notice
        {{ notice }}

      %p
        %b Title:
        {{ @task.title }}

      %p
        %b Body:
        {{ @task.body }}

      %p
        %b Due:
        {{ @task.due }}

      %p
        %b Complete:
        {{ @task.complete }}


    = link_to 'Edit', '#/tasks/edit', :class => "button radius" |
    = link_to 'Back', '', :class => "button radius"